site_name: What's So Cool About It?
site_description: A personal blog about things I want to talk about.
site_url: https://montagueka.github.io/
theme:
  name: material
  features:
    - navigation.sections

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - blog:
      blog_dir: .
  - search
  - tags
  - rss:
      match_path: posts/.*

      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

nav:
  - index.md