[project]
name = "blog"
version = "0.1.0"
description = "Personal Blog"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.5",
    "mkdocs-rss-plugin>=1.17.1",
]
